### ISSUE TITLE
Make the repldb client actually use nest-asyncio

### ISSUE THREAD

**Issue by Codemonkey51** [replit/replit-py#10]
It was there but then removed in a later commit it is helpful to solve some asyncio errors

**Comment by Scoder12** [comment]
I stopped using fancy code sharing because it was taking more time to do that than to just share async/sync code and to create the best experience for users with both async and sync sides. Due to this, `nest_asyncio` is no longer needed and has been removed from poetry.

**Comment by Codemonkey51** [comment]
Ok I’ll close this issue now
