### ISSUE TITLE
AttributeError: 'Request' object has no attribute 'is_authenticated'

### ISSUE THREAD

**Issue by dbarnes18** [replit/replit-py#110]
Using `replit.web`, I get this error trying to use the `@web.authenticated` method.

<img width="814" alt="Screenshot 2021-08-04 at 16 39 24" src="https://user-images.githubusercontent.com/83948303/128210799-380b68cd-23d6-4753-a5ae-4071440ced56.png">

Code:
```python
import flask
from replit import web, db

app = flask.Flask(__name__)

users = web.UserStore()

@app.route("/")
@web.authenticated
def index():
  hits = users.current.get("hits", 0) + 1
  users.current["hits"] = hits
  return f"You have visited this page {hits} times"

app.run(port=3000,host='0.0.0.0',debug=True)
```

**Comment by dbarnes18** [comment]
Errm, turns out that Replit installed version `3.1.0` of `replit-py`. I just ran `pip install --upgrade replit` to install `3.2.4`, and that worked perfectly.

**Comment by Scoder12** [comment]
Glad it worked, sorry about that
