### ISSUE TITLE
replit.web using usernames as keys

### ISSUE THREAD

**Issue by Coding-Cactus** [replit/replit-py#111]
From what I can see, the replit.web thingy uses usernames as keys for its database. The problem with that is that usernames can change on replit so if someone were to change their username, they would lose all their data on any sites which used this package. If replauth gives you user ids then you should probably use them instead so there is no chance of users losing data due to changing their username.

**Comment by Scoder12** [comment]
Interesting idea, however what if you wanted to get the usernames back somehow? You would have to store the ids as keys and the usernames in the values. It just adds a lot of complexity. Since changing usernames is quite rare, I think the impact is tolerable.
