### ISSUE TITLE
Error Working with DateTime UTC

### ISSUE THREAD

**Issue by DBULL7** [replit/replit-py#113]
👋 hi there, I'm giving replit db a shot and ran into an error saving utc timestamps. 

Steps to reproduce:

```python
from replit import db
import datetime

db['test'] = datetime.datetime.utcnow()
```
throws an exception: `ValueError: Circular reference detected`

I was able to solve by converting the timestamp to a string:
```python
db['test'] = str(datetime.datetime.utcnow())
```

Took me longer than I'd like to admit to debug as I rarely work with Python 😅 . If this is expected behavior feel free too close. 

Thanks for making such a cool tool!

**Comment by Scoder12** [comment]
Thanks! This behavior is intended, under the hood values are serialized using JSON so you should only pass JSON serializable objects to the DB. Your `str()` workaround is precisely what you should have done here, which is find an alternative method to serialize your object. Sorry this wasn't more clear!
