### ISSUE TITLE
[question] Repl-py-console 

### ISSUE THREAD

**Issue by ShowierData9978-Alt** [replit/replit-py#116]
Why does The repl console require you to use this  when you don't need it nor you want it because your using nothing in it , not even dependencies from it

**Comment by Scoder12** [comment]
I don't understand your question

**Comment by ShowierData9978-Alt** [comment]
I mean Why does repl automatically add this when I don't need it for my
python project

**Comment by Scoder12** [comment]
That is a question for them and not me...

**Comment by DillonB07** [comment]
They don't. This might be because of the new Nix repls, but this could be closed now?
