### ISSUE TITLE
AsyncDatabase RuntimeWarning: coroutine 'ClientSession.close' was never awaited

### ISSUE THREAD

**Issue by Jus-Codin** [replit/replit-py#118]
Using `AsyncDatabase` results in the following warning
```
/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py:80: RuntimeWarning: coroutine 
'ClientSession.close' was never awaited
  self.sess.close()
```
This can be replicated with the following code:
```py
import asyncio, os, replit
async def main():
  async with replit.AsyncDatabase(os.environ["REPLIT_DB_URL"]) as db:
    print(await db.keys())
    
asyncio.run(main())
```
This has previously been briefly mentioned in https://github.com/replit/replit-py/issues/115, but no fixes were done.
This should be easily fixed by adding `await` before the `self.sess.close()` in https://github.com/replit/replit-py/blob/master/src/replit/database/database.py#L80

Should I submit a pull request, or is there something I'm missing out?

**Comment by DillonB07** [comment]
Create a PR. They'll eventually get around to it and if it works, then it's just helpful.
