### ISSUE TITLE
Error when defining replit key

### ISSUE THREAD

**Issue by k0vu** [replit/replit-py#122]
It works successfully on replit, but when I use visual studio code, it'll
```
'NoneType' object does not support item assignment
```

**Comment by Scoder12** [comment]
The `REPLIT_DB_URL` environment variable must be set to use the database. To test locally, you can copy it from a repl using the shell.

**Comment by k0vu** [comment]
> The `REPLIT_DB_URL` environment variable must be set to use the database. To test locally, you can copy it from a repl using the shell.

what do I input into the shell specifically?

**Comment by Scoder12** [comment]
You can `echo $REPLIT_DB_URL` on replit and then set that as an environment variable locally.

**Comment by k0vu** [comment]
> echo $REPLIT_DB_URL

Thanks, in advance.

**Comment by k0vu** [comment]
It still isnt working, do I set `replit.database.db_url` to the received url?

**Comment by Scoder12** [comment]
No, you likely aren't setting the environment variable correctly.
