### ISSUE TITLE
Can't use "typing-extensions" with the Replit package installed

### ISSUE THREAD

**Issue by Vandesm14** [replit/replit-py#125]
With the `replit` package installed, installing the `typing-extensions` package isn't possible:
![image](https://user-images.githubusercontent.com/23623276/158650037-1e81d7a2-8500-4bc8-8ec2-a89719758857.png)

Steps to repro:
1. Use poetry to install the `replit` package
2. Install the `typing-extensions` package
3. Should produce the error in the above screenshot

**Comment by Vandesm14** [comment]
Bump: Is this actively maintained?

**Comment by techpixel** [comment]
Seems like a version conflict. This library needs to update its version of typing-extensions.

**Comment by ooliver1** [comment]
Using an older te is not sufficient, v4 has a lot of commonly used extensions like `NotRequired`

**Comment by Scoder12** [comment]
This library is not currently being maintained

**Comment by ooliver1** [comment]
Then why is it still used on replit?

**Comment by techpixel** [comment]
If you aren't maintaining it, you should probably add a warning.

**Comment by noneofyourbusiness1415252** [comment]
for now, do any of:
- `poetry add typing_extensions^3.7.4` - but many other packages would have updated to v4, so they become incompatible
- `poetry add git+https://github.com/noneofyourbusiness1415252/replit-py` (fork that bumps the `typing_extensions` version up)
- Wait for #131 to be merged

**Comment by totalhack** [comment]
This is causing issues for me as well. Combined with Poetry being ~forced on the user, is currently making Replit unusable in my case. Will try the workaround stated above but it's concerning that is necessary!

**Comment by noneofyourbusiness1415252** [comment]
this issue had finally been fixed. Run `poetry update replit` in Shell

**Comment by gkossakowski** [comment]
I don't think they fixed it, though:
```
Because no versions of replit match >3.3.1,<4.0.0
 and replit (3.3.1) depends on typing_extensions (>=3.7.4,<4.0.0), replit (>=3.3.1,<4.0.0) requires typing_extensions (>=3.7.4,<4.0.0).
And because sqlalchemy (2.0.20) depends on typing-extensions (>=4.2.0)
 and no versions of sqlalchemy match >2.0.20,<3.0.0, replit (>=3.3.1,<4.0.0) is incompatible with sqlalchemy (>=2.0.20,<3.0.0).
So, because python-template depends on both sqlalchemy (^2.0.20) and replit (^3.3.1), version solving failed.
```

**Comment by blast-hardcheese** [comment]
Pardon the bumps trying to resolve this, it appears that this is (finally!) solved. Thanks for your understanding:
```
~/...$ poetry add replit
Using version ^3.6.3 for replit

Updating dependencies
Resolving dependencies... (4.8s)

Package operations: 30 installs, 0 updates, 0 removals

  • Installing pycparser (2.22)
  • Installing cffi (1.16.0)
  • Installing frozenlist (1.4.1)
  • Installing idna (3.7)
  • Installing multidict (6.0.5)
  • Installing aiosignal (1.3.1)
  • Installing argon2-cffi-bindings (21.2.0)
  • Installing attrs (23.2.0)
  • Installing markupsafe (2.1.5)
  • Installing yarl (1.9.4)
  • Installing aiohttp (3.9.5)
  • Installing argon2-cffi (23.1.0)
  • Installing blinker (1.8.2)
  • Installing certifi (2024.2.2)
  • Installing charset-normalizer (3.3.2)
  • Installing click (8.1.7)
  • Installing cryptography (42.0.7)
  • Installing iso8601 (2.1.0)
  • Installing itsdangerous (2.2.0)
  • Installing jinja2 (3.1.4)
  • Installing pycryptodomex (3.20.0)
  • Installing urllib3 (2.2.1)
  • Installing werkzeug (3.0.3)
  • Installing aiohttp-retry (2.8.3)
  • Installing flask (3.0.3)
  • Installing protobuf (4.25.3)
  • Installing pyseto (1.7.8)
  • Installing requests (2.31.0)
  • Installing typing-extensions (4.11.0)
  • Installing replit (3.6.3)

Writing lock file
~/...$ poetry add typing-extensions
Using version ^4.11.0 for typing-extensions

Updating dependencies
Resolving dependencies... (0.3s)

No dependencies to install or update

Writing lock file
~/...$ 
```
