### ISSUE TITLE
replit thinking "telebot" is another package and downloading the wrong one

### ISSUE THREAD

**Issue by shroomwastaken** [replit/replit-py#126]
I tried getting the bot to run on repl.it, but when having ```import telebot``` in the code, replit thinks that I want to use [this](https://pypi.org/project/telebot/) package, instead of [pyTelegramBotAPI](https://pypi.org/project/pyTelegramBotAPI/). So, when running the program, replit automatically installs and starts trying to use that other package in the program, leading it to fail when calling ```message_handler```, an attribute of the TeleBot class in the ```pyTelegramBotAPI``` package, but not in telebot

Example code:
```python
import telebot
import os

bot = telebot.TeleBot(os.environ["token"])

@bot.message_handler(commands=["start"])
def hi(message):
    bot.send_message(chat_id=message.chat.id, text="hello there, this is an example"

bot.infinity_polling()
```

Error:
![image_2022-03-17_16-44-08](https://user-images.githubusercontent.com/59111626/158865872-11f456c1-bad3-4fd0-a001-3f62c32937e0.png)

I am writing ```import telebot``` here instead of ```import pyTelegramBotAPI``` because:
1. It says so in the docs of the pyTelegramBotAPI package
2. It gives a ModuleNotFound error if I write ```import pyTelegramBotAPI```

**Comment by shroomwastaken** [comment]
Just realized this isn' the right place to post this. Oops!)

**Comment by DrContiello** [comment]
You are right. i have the same issue here, and i can't find the answer...
