### ISSUE TITLE
Using replit database on a different account doesnt work

### ISSUE THREAD

**Issue by de-contained** [replit/replit-py#127]
I am trying to make an email verification system (which works) on a different account, but I cant hide the email and password without being interrupted by this error.

```
TypeError: 'NoneType' object is not subscriptable
```

The code I am using, and tried.

**Replit.DB**
```py
replit.db['email'] = ""
replit.db['password'] = ""
```
**OS**
```py
email    = os.environ['EMAIL']
password = os.environ['PASSWORD']
```

**Comment by techpixel** [comment]
Please add more information, since it's vague where the error is coming from. Do you have a repl or a code snippet to share?

**Comment by noneofyourbusiness1415252** [comment]
this has happened to me when `REPLIT_DB_URL` isn't set - when you're using the repl without logging in, but I don't know why using a different account wouldn't work

**Comment by techpixel** [comment]
Yes, replit_db does not work if you are not logged in. You could try using repl auth or identity.
