### ISSUE TITLE
looping doesn't work

### ISSUE THREAD

**Issue by dobby472375892365** [replit/replit-py#128]
I'm trying to loop music and it only plays once. I also went to a program that can adjust volume and how many times it loops. when I add loop to it, it only plays once.

**Comment by blast-hardcheese** [comment]
See #219. We removed our custom in-repl audio in favor of guiding users towards more standard, better supported tooling (see [pulsectl](https://pypi.org/project/pulsectl/) on pypi, as well as [this blog post on using "system audio"](https://blog.replit.com/system-audio)).
