### ISSUE TITLE
replit Python audio library not working

### ISSUE THREAD

**Issue by CSGuy57** [replit/replit-py#129]
When trying to play an audio file in Python, I receive the following: TimeoutError: Source was not created within 2 seconds. I have verified this across multiple replits with wav files of various lengths and always get the same thing.

This error can be observed here: https://replit.com/@CSGuy57/py-audio-demo#main.py

**Comment by blast-hardcheese** [comment]
See #219. We removed our custom in-repl audio in favor of guiding users towards more standard, better supported tooling (see [pulsectl](https://pypi.org/project/pulsectl/) on pypi, as well as [this blog post on using "system audio"](https://blog.replit.com/system-audio)).
