### ISSUE TITLE
Replit audio error

### ISSUE THREAD

**Issue by Quantum-Codes** [replit/replit-py#138]
**Problem:**
When using the `audio` module from this package, a `FileNotFoundError` occurs

**Code sample:**
```py
from replit import audio

x = audio.play_file("flashback.mp3")
print(x)
```
**Error:**
![Screenshot_20230403-195442_Replit](https://user-images.githubusercontent.com/87054411/229541314-20a0d8a4-fbcb-4a96-90e6-788d629823de.jpg)

**Comment by blast-hardcheese** [comment]
See #219. We removed our custom in-repl audio in favor of guiding users towards more standard, better supported tooling (see [pulsectl](https://pypi.org/project/pulsectl/) on pypi, as well as [this blog post on using "system audio"](https://blog.replit.com/system-audio)).
