### ISSUE TITLE
Cannot get or delete keys which contain question marks '?'

### ISSUE THREAD

**Issue by chao-master** [replit/replit-py#17]
**Steps to reproduce:**
An example Repl.it can be found here: https://repl.it/@Ripp/CannotDeleteExample
1. Store a key/value in the database with a question mark in the key
    `db["test ? with mark"] = 1`
2. Try to retrive or delete the key:
    `print(db["test ? with mark"])` or  
    `del db["test ? with mark"]`

**Expected:**
They key is retrived/deleted as apporiate

**Actual:**
A KeyError is raised, however the key is present as can be verified by inspecting keys (`db.keys()`)

**Work around:**
The user can pre escape the `?` character to `%3F`, after which it works fine.

**Comment by Scoder12** [comment]
Oops, async version does this right but sync does not. They should both have `urllib.parse.quote(key)`.
