### ISSUE TITLE
replit-py not compatible with Flask 3.0.0

### ISSUE THREAD

**Issue by DaInfLoop** [replit/replit-py#188]
https://www.reddit.com/r/replit/s/7lOFt5gL3V

# Post content:
Has anyone run into an issue where they cannot import the latest version of Flask and Replit. When I try to import flask I get this error:

`Because replit (3.3.2) depends on Flask (>=2.0.0,<3.0.0)`

 `and no versions of replit match >3.3.2,<4.0.0, replit (>=3.3.2,<4.0.0) requires Flask (>=2.0.0,<3.0.0).`

`So, because python-template depends on both replit (^3.3.2) and flask (^3.0.0), version solving failed.`

`exit status 1`

I've tried installing a previous version of flask but then when I try and start the server with this code:

`from replit import web, db`

`from flask import Flask`

`app = Flask(__name__)`

[`web.run`](https://web.run)`(app)`

&#x200B;

I get the following error:

`Traceback (most recent call last):`

  `File "/home/runner/IntrepidAltruisticMultiprocessing/main.py", line 6, in <module>`

[`replit.web.run`](https://replit.web.run)`(app)`

  `File "/home/runner/IntrepidAltruisticMultiprocessing/.pythonlibs/lib/python3.10/site-packages/replit/web/app.py", line 62, in run`

`if change_encoder and app.json_encoder is flask.json.JSONEncoder:`

`AttributeError: 'Flask' object has no attribute 'json_encoder'`

Any help would be much appreciated!

**Comment by noneofyourbusiness1415252** [comment]
> `replit (>=3.3.2,<4.0.0) requires Flask (>=2.0.0,<3.0.0)`

(for reference) run in Shell:
```bash
poetry add Flask@^2.0.0
```
> `'Flask' object has no attribute 'json_encoder'`

run in Shell:
```bash
poetry update replit
```
