### ISSUE TITLE
Handle Database Errors in a more pythonic and traditional way.

### ISSUE THREAD

**Issue by techpixel** [replit/replit-py#2]
Instead of basic input prompt to handle errors, allow users to use a try and except as an easier way to handle errors and debug. Also makes database class much more quieter

**Comment by Scoder12** [comment]
Sure. Right now the only way to suppress the prompt is use the `discard_bad_data` kwarg, but I'll add one that throws an exception if you want custom behavior.

**Comment by Codemonkey51** [comment]
maybe the throw arg can be set globally,
that would also let other args to have default global ones the user can ser

**Comment by Scoder12** [comment]
If its too tedious you can subclass JSONKey to override the default: 
```py
class MyJSONKey(db.JSONKey):
  def __init__(self, key, dtype):
    super().__init__(db, key, dtype, the_tedious_kwarg_i_dont_want_to_set=True)
```
and replace `db.jsonkey(...)` with `MyJSONKey(...)` since `db.jsonkey` just initializes a JSONKey instance under the hood.

**Comment by techpixel** [comment]
On top of this, maybe change value defaulting to a raise exception too

**Comment by Scoder12** [comment]
@techpixel what do you mean by that?

**Comment by techpixel** [comment]
```py
        try:
            read = self.db[self.key]
        except KeyError:
            print(
                f"Database key {self.key} not set, setting it to default value"
            )
            default = self._default()
            self.db[self.key] = default
            return default
```
Line 74-82, when there's a key error, it justs uses a user-defined function to fix the issue. Instead raise an error so the user can fix it @Scoder12
