### ISSUE TITLE
Feature Request: Allow ReplDB to be configured from external file

### ISSUE THREAD

**Issue by techpixel** [replit/replit-py#21]
Allow advanced configuration of ReplDB from a external file, possibly named `.db`

**Comment by Codemonkey51** [comment]
What would this file? It seems like a good idea, but idk what is would do

**Comment by Codemonkey51** [comment]
it*

**Comment by techpixel** [comment]
It would contain some configuration basic options such as `discard_bad_data` and also include some new options such as an option to prevent the database being overloaded with too many requests.

**Comment by Scoder12** [comment]
Why not parse this yourself? Why should it be part of the library?

**Comment by techpixel** [comment]
**1** I was thinking it would be much more simpler and accessible having everything in a separate file instead of going back to the code and modifying it.
**2** I thought it would be better to have something like this in the case that there are more than one database in different parts/files. It would be easier to have everything under a global option and then in the code the user could provide a local option that overrides the current global option.

**Comment by Codemonkey51** [comment]
**1** ok that makes some sense, but that could be easily implemented in the program
**2** There is only 1 repl db per repl unless you hardcode db urls, which you shouldn't do

**Comment by Codemonkey51** [comment]
I'm not saying it's a bad idea, but just that it may not be needed

**Comment by techpixel** [comment]
I should probably write my own external library for this.

**Comment by Codemonkey51** [comment]
> I should probably write my own external library for this.

Yeah that might work best

**Comment by Scoder12** [comment]
Yeah, this would be better suited for an external library.
