### ISSUE TITLE
Audio is not working properly

### ISSUE THREAD

**Issue by seamuskills** [replit/replit-py#22]
I'm not sure why or what I'm doing wrong but the audio on repl (in a python repl) will not play. I don't know why it won't play, I have 0 ideas if it's the library or the repl. you can find it here: https://repl.it/@SeamusDonahue/test-sound#main.py

**Comment by seamuskills** [comment]
also, I'm new to Github so I don't know how to add labels, please do not disregard this based on the lack of labels.

**Comment by Codemonkey51** [comment]
> also, I'm new to Github so I don't know how to add labels, please do not disregard this based on the lack of labels.

I don't think labels affect bug processing at all

**Comment by Scoder12** [comment]
1. Check if you have explorer mode enabled [here's how to enable it](https://repl.it/talk/announcements/Become-an-Explorer/6180)
2. If you already had that on, please post a repl link

**Comment by Codemonkey51** [comment]
@Scoder12 link is on the issue: https://repl.it/@SeamusDonahue/test-sound#main.py

**Comment by Scoder12** [comment]
Your code is exiting before the audio has a chance to play. You need something to block it from exiting. 
But even after adding that, it doesn't seem to work with your specific audio file, not sure why.

**Comment by Scoder12** [comment]
Maybe its something to do with it being an mp3, but the docs say that mp3s are supported.

**Comment by AllAwesome497** [comment]
Looking at your repl there's 2 issues. 

1: Your code exits before the audio has time to play. Once the code exits, we stop listening for audio. 
To wait until audio finishes playing you can use something like:

```py 
import time
from replit import audio

source = audio.play_file("victory.mp3")
time.sleep(1) # Wait a moment for the file to be registered

while source.get_remaining().microseconds != 0: # microseconds will equal 0 when the source is done playing.
    time.sleep(.1) # wait a moment so we don't spam the reads which can sometimes cause an error
```

2: Your mp3 file is not valid.
  
```bash
~/test-sound-1$ ffprobe victory.mp3 
ffprobe version 3.4.8-0ubuntu0.2 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, wav, from 'victory.mp3':
  Duration: 00:00:01.21, bitrate: 176 kb/s
    Stream #0:0: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 22050 Hz, 1 channels, u8, 176 kb/s
```

> Input #0, wav, from 'victory.mp3':

this should say "Input #0, mp3...". Some sort of encoding error. 
You can fix this by running `ffmpeg -i victory.mp3 newvictory.mp3`
Once you do that you can get rid of the old file and replace it with the new one.
(note - this is bash and must be run from shell)
My repl - https://repl.it/@AllAwesome497/test-sound-1#main.py

**Comment by chrischma** [comment]
Is `audio` still available in 2024? 

i tried using it with the code of the official tutorial [video](https://www.youtube.com/watch?v=CuIV2-ivg0U), and i get an import error.

```python
from replit import audio

audio.play_file("pop.mp3")

while True:
  pass
```

Also, the [documentation](https://docs.replit.com/repls/audio) seems to be offline...
