### ISSUE TITLE
[Request] Update dictionary key-value pairs in repl db without updating the entire dictionary

### ISSUE THREAD

**Issue by patrickscoleman** [replit/replit-py#26]
I would like to be able to do something like this:

```python
from replit import db
db["test"] = {"a": "hello"}
# I want to do this.
db["test"]["a"] = "world"
print(db["test"])
```

And get the following output:

```python
{"a": "world"}
```

But instead I will get:

```python
{"a": "hello"}
```

The following code would work:

```python
from replit import db
db["test"] = {"a": "hello"}
# I must use a temporary variable and then update the entire dictionary in the database.
temp = db["test"]
temp["a"] = "world"
db["test"] = temp
print(db["test"])
```

**Comment by Codemonkey51** [comment]
Hmmm 🤔 I can try to debug and see what happens here, and try to find a possible fix

**Comment by kennethreitz42** [comment]
This is basically expected behavior, in my opinion. I believe the solution is to make `JSONKey` immutable, e.g. raising an exception when modifications are attempted to be made.

**Comment by Scoder12** [comment]
This actually worked at one point but not sure what happened as the code has changed a ton
