### ISSUE TITLE
Replit DB Floating Point Issue

### ISSUE THREAD

**Issue by cbrewster** [replit/replit-py#75]
Hey @Scoder12, we got a bug report that retrieving floating point values from replit db is broken in the latest version (v3) of this package. They say this worked in v2. Are you able to take a look?

> Version 3 of the replit package throws an error when attempting to retrieve floats from the replit db

**Comment by Scoder12** [comment]
That is #73. Fixed in latest master but has yet to be published to PyPi. I will try to make that happen ASAP.

**Comment by cbrewster** [comment]
Thanks!
